### PR TITLE
Re-add config flow and fix setup from #2

### PR DESCRIPTION
**Pull request by raman325**
Fixes error in #2

### CODE REVIEW

**Comment by raman325** [comment]
this is working on my end

**Comment by koush** [comment]
Had the IP wrong when I was testing and then didn't realize it still needed a restart. 
So, looks like it works but there should probably be a notification of some sort after the service is added.

**Comment by raman325** [comment]
what did you need the restart for? to update your configuration.yaml and have that take effect?

**Comment by koush** [comment]
The card was not functional until the restart. Neither was the entry for the panel that was already there.

**Comment by raman325** [comment]
hmm that seems like a bug I can't think of why that should be the case. I will do some testing tonight. I'm also going to have it set up the panel automatically in a future PR

**Pull request merged**
